# Generated by Django 4.2.30 on 2026-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.IntegerField()),
                ('a_sx', models.IntegerField()),
                ('a_sy', models.IntegerField()),
                ('b_id', models.IntegerField()),
                ('b_sx', models.IntegerField()),
                ('b_sy', models.IntegerField()),
                ('a_steps', models.JSONField(default=list)),
                ('b_steps', models.JSONField(default=list)),
                ('gamemap', models.JSONField(default=list)),
                ('loser', models.CharField(max_length=10)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
