# Generated by Django 4.2.30 on 2026-04-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=1500),
        ),
    ]
