# Generated by Django 4.2.30 on 2026-04-18 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='a_id',
            field=models.ForeignKey(db_column='a_id', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='b_id',
            field=models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_b', to=settings.AUTH_USER_MODEL),
        ),
    ]
