[uwsgi]
  socket          = 127.0.0.1:8001
  chdir           = /home/abiding/snake
  wsgi-file       = snake/wsgi.py
  master          = true
  processes       = 2
  threads         = 5
  vacuum          = true
